resolver: nightly-2021-07-31
compiler: ghc-9.0.1
packages:
- .

extra-deps:
- brick-skylighting-0.3
- git: https://github.com/mlang/chessIO.git
  commit: b6588abeffa360f85a4ed6bc271c189d71853e68
- o-clock-1.2.1
